# Generated by Django 3.0.4 on 2020-04-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clear_cut', '0002_auto_20200410_1303'),
        ('media_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaitem',
            old_name='clear_cut_media_url',
            new_name='media_url_clear_cut',
        ),
        migrations.RenameField(
            model_name='mediaitem',
            old_name='original_media_url',
            new_name='media_url_original',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='clear_cut_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clear_cut.ClearCutConfig'),
        ),
    ]
