# Generated by Django 3.0.4 on 2020-06-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0002_auto_20200410_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='media_url_clear_cut',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='media_url_original',
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url_original', models.URLField()),
                ('media_url_clear_cut', models.URLField()),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_management.MediaItem')),
            ],
        )
    ]
