# Generated by Django 3.0.4 on 2020-06-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0004_auto_20200622_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearcut_image', to='media_management.MediaItem'),
        ),
    ]
