# Generated by Django 3.0.4 on 2020-06-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0005_auto_20200622_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='clear_cut_images',
            field=models.ManyToManyField(related_name='_mediaitem_clear_cut_images_+', to='media_management.MediaItem'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_cut_image', to='media_management.MediaItem'),
        ),
    ]
