# Generated by Django 3.0.4 on 2020-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0006_auto_20200622_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='clear_cut_images',
            field=models.ManyToManyField(to='media_management.MediaItem'),
        ),
    ]
