# Generated by Django 3.0.4 on 2020-06-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0007_auto_20200622_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='clear_cut_images',
        ),
    ]
